### ISSUE TITLE
how to rebuild build/examples.js and build/simulator.js

### ISSUE THREAD

**Issue by jeromeetienne** [borismus/ray-input#10]
Hey boris,

I am struggling to rebuild the example/simulator... all the browserify and co is black magic to me :)

i have seen some stuff in the package.json scripts, but they dont work. and include some '[]' which makes me think they are more template rather than actual commands.

Can you elaborate how you build examples/simulator ? 

thanks :)

**Comment by jeromeetienne** [comment]
Here is the error im getting while trying the package.json script btw... just it case it help :)

```
jeromeetienne@jerome-macbook:~/webwork/ray-input(master)$ watchify -vdt babelify --presets es2015 src/example/main.js -o build/example.js

/Users/jeromeetienne/webwork/ray-input/src/example/main.js:16
import MenuRenderer from './renderer.js';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by jeromeetienne** [comment]
now it works, im not why. maybe i installed some new package without knowing it.

All in all, it seemed to be a local error... 

sorry about the noise, excelent job btw :)

if you need some work to be done on this library, i would like to participate!

**Comment by borismus** [comment]
Thanks Jerome. As for what needs to be done, see end of README.
