### ISSUE TITLE
cardboard button not firing on touch unless I remove e.preventDefault() on touchEnd;

### ISSUE THREAD

**Issue by bunnybones1** [borismus/ray-input#14]
I've had to comment out ray-controller.js:200 to get the onScreen buttons to work
```
  onTouchEnd_(e) {
    this.endDragging_();

    // Prevent synthetic mouse event from being created.
    // e.preventDefault();
    this.isTouchActive = false;
  }
```

Is there another way to get them to work without doing this? Hard to believe I'm the only one with this problem unless I'm doing something wrong. :)

**Comment by arturitu** [comment]
@bunnybones1 I have the same issue here (you are not alone).

**Comment by arturitu** [comment]
And only works with this commented line with Chrome Beta, isn't it?

**Comment by borismus** [comment]
Sorry for delay, which on screen buttons are you talking about?

**Comment by arturitu** [comment]
@borismus fullscreen and cardboard buttons on the bottom right

**Comment by klausw** [comment]
Proposed fix here: https://github.com/borismus/ray-input/pull/26
