### ISSUE TITLE
Vive gamepad not registering

### ISSUE THREAD

**Issue by HalfdanJ** [borismus/ray-input#4]
Can't get it to work on our Vive setup in latest webvr chromium. The controllers work on the webvr.info samples. 

`navigator.getGamepads()` in ray-controller.js is only returning an array of 4 `null`. Will do some more debugging on it.

**Comment by HalfdanJ** [comment]
Firmware mismatch was the issue

**Comment by borismus** [comment]
Ah, awesome!
