### ISSUE TITLE
repository link broken ?

### ISSUE THREAD

**Issue by jeromeetienne** [borismus/ray-input#7]
the link of this repository is http://smus.com/ray-input-default-webvr-interaction/ 

It replies 404 to me. should it be http://smus.com/ray-input-webvr-interaction-patterns/ ? 

Thanks for this amazing work btw :)

**Comment by jeromeetienne** [comment]
in the readme.md, there is a http://smus.com/ray-sane-defaults-vr-input link which seems broken too

**Comment by jeromeetienne** [comment]
https://github.com/borismus/ray-input/pull/6 seems to handle the one in the README.md

**Comment by borismus** [comment]
Thanks!
